# Generated by Django 4.1.4 on 2023-01-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
